### ISSUE TITLE
Todo Task: Frontend

### ISSUE THREAD

**Issue by Sanchitbajaj02** [RCC-MRU/todo-app-frontend#31]
- [ ] Fix buttons
- [ ] Add buttons of the star, double-tick, delete on show task list page
- [ ] Add popup model on show task list page
- [ ] Look for the add todo
      - show data on the console
- [ ] __Learn React Hooks__
